### ISSUE TITLE
A register problem while deploy on a offline server

### ISSUE THREAD

**Issue by SakakiChizuru** [AethLi/mineauth#1]
Unregistered error will randomly occur everytime connected to the server even has been registered.
No idea how it happens.

**Comment by SakakiChizuru** [comment]
ADDTION: 
Unregister on current server error occurs when Client shutdown and restart again,
if only disconnect from server it work fine.
BTW, MineAuth only installed on server side.

**Comment by AethLi** [comment]
I cannot reproduce this problem.
Could you provide more information(what minecraft version and forge version), or logs file if exists.

**Comment by SakakiChizuru** [comment]
> I cannot reproduce this problem.
> Could you provide more information(what minecraft version and forge version), or logs file if exists.

MC is 1.16.4 and Forge is 5.1.28,

Our first installing is basic. Added Authmod into server mods folder and modified the kick delay time.
And then all players has the same problem,
My server hoster told me if server has reboot operation then all of players must Reregister.
And my situation was wired, sometime I make a clean restart of MC and join the server it tell me to register but sometime not.

I'm just tried modify config's "columnIdentifier", use "USERNAME" instead of "EMAIL".
My hoster told me got 1 db exceptions
And currently seems it can correct this problem(Server is restarted 3 times and I got clean launch of MC 3 times).
Now the problem is, When server restarted, I can actually using "/login" to login, but chatwindow red text tips me "Unexpected error occur while execute command"(I'm not using english version so idk what's the correct text will pop but just meaning like that). Even mc told me something wrong but I still got logged in.

Here's what's exact server log, my hoster's using smartphone remote control so he can't got fully log of server but this paragraph.
It's just after Iexecuted "/login" command, and "columnIdentifier" is set to "USERNAME", and also "Unregister on this server" never shows.
Here's the serverside exception log:

`[121��2021 00:12:36.196] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:649]: org.h2.jdbc.JdbcSQLSyntaxErrorException: Duplicate column name "USERNAME"; SQL statement:
update `PLAYERS` SET `PASSWORD`='b30de29c828665d7bc3c0f784e262d2b',`LAST_LOGIN`='2021-01-12 00:12:36',`USERNAME`='SakakiChizuru',`BANNED`='false',`USERNAME`='SakakiChizuru',`UUID`='d9346da8-f809-345b-bbd6-e4cb43a10001' [42121-200]
[121��2021 00:12:36.197] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:649]: 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
[121��2021 00:12:36.198] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:649]: 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
[121��2021 00:12:36.199] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:649]: 	at org.h2.message.DbException.get(DbException.java:205)
[121��2021 00:12:36.199] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:649]: 	at org.h2.message.DbException.get(DbException.java:181)
[121��2021 00:12:36.200] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:649]: 	at org.h2.command.dml.Update.setAssignment(Update.java:92)
[121��2021 00:12:36.200] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:649]: 	at org.h2.command.Parser.parseUpdateSetClause(Parser.java:1327)
[121��2021 00:12:36.200] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:649]: 	at org.h2.command.Parser.parseUpdate(Parser.java:1290)
[121��2021 00:12:36.201] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:649]: 	at org.h2.command.Parser.parsePrepared(Parser.java:1005)
[121��2021 00:12:36.201] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:649]: 	at org.h2.command.Parser.parse(Parser.java:843)
[121��2021 00:12:36.202] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:649]: 	at org.h2.command.Parser.parse(Parser.java:815)
[121��2021 00:12:36.202] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:649]: 	at org.h2.command.Parser.prepareCommand(Parser.java:738)
[121��2021 00:12:36.203] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:649]: 	at org.h2.engine.Session.prepareLocal(Session.java:657)
[121��2021 00:12:36.203] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:649]: 	at org.h2.engine.Session.prepareCommand(Session.java:595)
[121��2021 00:12:36.204] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:649]: 	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
[121��2021 00:12:36.205] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:649]: 	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:76)
[121��2021 00:12:36.205] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:649]: 	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:352)
[121��2021 00:12:36.206] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:649]: 	at cn.aethli.mineauth.common.utils.DataUtils.updateById(DataUtils.java:241)
[121��2021 00:12:36.206] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:649]: 	at cn.aethli.mineauth.command.account.LoginCommand.run(LoginCommand.java:55)
[121��2021 00:12:36.207] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:649]: 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262)
[121��2021 00:12:36.207] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:649]: 	at net.minecraft.command.Commands.func_197059_a(Commands.java:217)
[121��2021 00:12:36.207] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:649]: 	at net.minecraft.network.play.ServerPlayNetHandler.func_147361_d(ServerPlayNetHandler.java:1119)
[121��2021 00:12:36.208] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:649]: 	at net.minecraft.network.play.ServerPlayNetHandler.func_244548_c(ServerPlayNetHandler.java:1102)
[121��2021 00:12:36.208] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:649]: 	at net.minecraft.network.play.ServerPlayNetHandler.func_147354_a(ServerPlayNetHandler.java:1081)
[121��2021 00:12:36.209] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:649]: 	at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(SourceFile:36)
[121��2021 00:12:36.209] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:649]: 	at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(SourceFile:9)
[121��2021 00:12:36.210] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:649]: 	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21)
[121��2021 00:12:36.210] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:649]: 	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
[121��2021 00:12:36.210] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:649]: 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
[121��2021 00:12:36.211] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:649]: 	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
[121��2021 00:12:36.211] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:649]: 	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:733)
[121��2021 00:12:36.212] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:649]: 	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159)
[121��2021 00:12:36.212] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:649]: 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
[121��2021 00:12:36.213] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:649]: 	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:716)
[121��2021 00:12:36.213] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:649]: 	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:710)
[121��2021 00:12:36.213] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:649]: 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103)
[121��2021 00:12:36.214] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:649]: 	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:695)
[121��2021 00:12:36.214] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:649]: 	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:645)
[121��2021 00:12:36.215] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:649]: 	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232)
[121��2021 00:12:36.215] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:649]: 	at java.base/java.lang.Thread.run(Thread.java:830)`

**Comment by SakakiChizuru** [comment]
*Forge 35.1.28

**Comment by SakakiChizuru** [comment]
Here's log before exception log I'm just posted, seems working normally, and there's no exeption log with MineAuth before this:

`[121��2021 00:12:04.224] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: SakakiChizuru lost connection: Disconnected
[121��2021 00:12:04.225] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: [Brigadier] SakakiChizuru left the game
[121��2021 00:12:15.225] [Netty Server IO #7/INFO] [codechicken.lib.config.ConfigSyncManager/]: Skipping config sync, No mods have registered a syncable config.
[121��2021 00:12:20.223] [Server thread/INFO] [net.minecraftforge.common.AdvancementLoadFix/]: Using new advancement loading for net.minecraft.advancements.PlayerAdvancements@2ab0c1ca
[121��2021 00:12:20.304] [Server thread/INFO] [net.minecraft.server.management.PlayerList/]: SakakiChizuru[/220.169.96.10:11700] logged in with entity id 1334 at (-609.1727816026341, 104.0, 403.6351285299451)
[121��2021 00:12:20.316] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: [Brigadier] SakakiChizuru joined the game`

**Comment by SakakiChizuru** [comment]
说英文累...留个联系方式,今天白天能拿到完整LOG..
@AethLi

**Comment by AethLi** [comment]
邮件到selcarpa@gmail.com，我回复你详细联系方式

**Comment by AethLi** [comment]
seems you used a exists column name, make Connection::prepareStatement got a wrong result.

**Comment by AethLi** [comment]
Added duplicate column name check
